<a href="https://colab.research.google.com/github/div-yash/Breast-Cancer-Prediction-using-PyTorch/blob/main/Breast_Cancer_Prediction_using_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Importing the dependencies

import torch
import torch.nn as nn
import torch.optim as optim

import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


Device Configuration:


In [2]:
# check for CUDA availability
device=torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using Device:",{device})

Using Device: {device(type='cuda')}


In [3]:
# Data collection and preprocessing

#loading dataset
data=load_breast_cancer()
x=data.data
y=data.target

In [4]:
print(x)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [5]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 0 1 0 1 1 0 

In [6]:
print(data)

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
 

In [7]:
print(y[:5])

[0 0 0 0 0]


In [8]:
#splitting data set into training and  test test
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [9]:
print(x.shape)
print(x_test.shape)
print(x_train.shape)

(569, 30)
(114, 30)
(455, 30)


In [10]:
# standardize the data using standard scaler
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [11]:
type(x_test)

numpy.ndarray

numpy.ndarray cannot be used in pytorch therefore we convert this into tensors

In [12]:
#  into PyTorch tensors and move it to gpu
x_train=torch.tensor(x_train,dtype=torch.float32).to(device)
y_train=torch.tensor(y_train,dtype=torch.float32).to(device)
x_test=torch.tensor(x_test,dtype=torch.float32).to(device)
y_test=torch.tensor(y_test,dtype=torch.float32).to(device)


neural network architecture:
---

### 🔹 Importing and defining the class

```python
class NeuralNet(nn.Module):
```

* You’re defining a neural network by subclassing `torch.nn.Module` (the base class for all PyTorch models).
* This allows you to build layers and define how data flows through them.

---

### 🔹 The constructor

```python
def __init__(self, input_size, hidden_size, output_size):
    super(NeuralNet, self).__init__()
```

* `__init__` sets up the layers of your network.
* `super(...)` initializes the parent class (`nn.Module`) so PyTorch can track layers/parameters.

---

### 🔹 Layers

```python
self.fc1 = nn.Linear(input_size, hidden_size)
```

* A **fully connected (dense) layer** that maps the input features to hidden features.
* Example: if `input_size=10` and `hidden_size=16`, this layer has a weight matrix of shape `[16, 10]`.

```python
self.relu = nn.ReLU()
```

* **ReLU activation function**: replaces negative values with 0, keeps positives as-is.
* Adds non-linearity so the network can learn complex relationships.

```python
self.fc2 = nn.Linear(hidden_size, output_size)
```

* Another fully connected layer that maps hidden layer → output.
* Example: if `hidden_size=16` and `output_size=1`, it has weights `[1, 16]`.

```python
self.sigmoid = nn.Sigmoid()
```

* **Sigmoid activation function** squashes values between `0` and `1`.
* Commonly used for **binary classification** (probability-like output).

---

### 🔹 Forward pass

```python
def forward(self, x):
    out = self.fc1(x)
    out = self.relu(out)
    out = self.fc2(out)
    out = self.sigmoid(out)
    return out
```

This defines how data flows through the network:

1. `x` → `fc1` → `out` (linear transform: `Wx + b`)
2. `ReLU` applied (non-linearity)
3. Pass through `fc2`
4. Apply `Sigmoid` → compress final outputs between 0–1
5. Return predictions

So if you pass a batch of inputs, the model outputs a batch of probabilities.

---

### 🔹 Example

```python
model = NeuralNet(input_size=10, hidden_size=16, output_size=1)
x = torch.randn(5, 10)  # batch of 5 samples with 10 features each
y = model(x)
print(y)
```

Output → something like:

```
tensor([[0.5234],
        [0.4128],
        [0.8765],
        [0.1342],
        [0.6891]], grad_fn=<SigmoidBackward>)
```

Each number is between **0 and 1**, representing a predicted probability.

---

✅ In short:
our code builds a **2-layer feedforward neural network** with ReLU in the hidden layer and Sigmoid in the output, making it suitable for **binary classification tasks**.


In [23]:
#define the neural architecture

class NeuralNet(nn.Module):
  #inherit the parameters and methods of nn.module class to NeuralNet class

  def __init__(self,input_size,hidden_size,output_size):
    super(NeuralNet,self).__init__()
    self.fc1=nn.Linear(input_size,hidden_size)
    self.relu=nn.ReLU()
    self.fc2=nn.Linear(hidden_size,output_size)
    self.sigmoid=nn.Sigmoid()

  def forward(self,x):
    out=self.fc1(x)
    out=self.relu(out)
    out=self.fc2(out)
    out=self.sigmoid(out)

    return out


In [24]:
# define hyperparameters:
input_size=x_train.shape[1] #30
hidden_size=64 #let say ..can be 32 as well
output_size=1 #sigmoid..binary classification
learning_rate=0.001
num_epochs=100

In [25]:
#initialize the neural network and move it to GPu
model=NeuralNet(input_size,hidden_size,output_size).to(device)


NeuralNet(input_size, hidden_size, output_size)

Creates an instance of your neural network class.

Example: if you set input_size=10, hidden_size=16, output_size=1, it builds the exact architecture you defined earlier.

.to(device)

Moves the entire model (all layers, weights, and biases) to the specified device:

If device = torch.device("cpu"), it keeps the model on CPU.

If device = torch.device("cuda"), it moves the model to GPU for faster training.

You can also use "mps" on Apple Silicon (M1/M2/M3 chips).

In [26]:
#define loss and optimizer

criterion =nn.BCELoss()
optimizer=optim.Adam(model.parameters(),lr=learning_rate)


### 🔹 Loss function

```python
criterion = nn.BCELoss()
```

* `BCELoss` = **Binary Cross-Entropy Loss**.
* It measures how well the model’s predicted probability matches the true label (0 or 1).
* Formula:
  [
  \text{Loss} = - \frac{1}{N} \sum \big[ y \cdot \log(p) + (1-y) \cdot \log(1-p) \big]
  ]
  where:

  * ( y ) = true label (0 or 1)
  * ( p ) = model prediction (between 0 and 1 after sigmoid)

✅ Suitable for **binary classification** problems.

⚠️ Note: Since our model already applies `sigmoid` in `forward`, you should use `nn.BCELoss`.
But if you **remove sigmoid** from the model’s `forward`, it’s better to use:

```python
criterion = nn.BCEWithLogitsLoss()
```

because it combines `sigmoid + BCELoss` in one step (more numerically stable).

---

### 🔹 Optimizer

```python
optimizer = optim.Adam(model.parameters(), lr=learning_rate)
```

* `optim.Adam` = Adam optimizer (Adaptive Moment Estimation).
* It updates the model’s weights using gradient descent, but adapts learning rates for each parameter.
* `model.parameters()` gives the optimizer access to all learnable parameters (weights & biases).
* `lr=learning_rate` sets the step size for updates (commonly 0.001).

---

### 🔹 Training step (conceptual flow)

1. **Forward pass**

   ```python
   outputs = model(inputs)
   loss = criterion(outputs, labels)
   ```

   * Compute predictions and loss.

2. **Backward pass**

   ```python
   optimizer.zero_grad()  # reset gradients
   loss.backward()        # compute gradients
   optimizer.step()       # update weights
   ```

3. **Repeat** for all batches/epochs.

---

✅ So, our setup means:

* Use **Binary Cross Entropy** to measure prediction error.
* Use **Adam optimizer** to minimize this loss by updating weights.


In [32]:
#training the neural network:

for epoch in range(num_epochs):
  model.train()
  optimizer.zero_grad()
  outputs=model(x_train)
  loss=criterion(outputs,y_train.view(-1,1))
  loss.backward()
  optimizer.step()

  #calculate accuracy
  with torch.no_grad():
    predicted=outputs.round()
    correct = (predicted == y_train.view(-1,1)).float().sum()
    accuracy = correct / y_train.size(0)

  if (epoch+1) % 10 == 0:
    print(f"Epoch [{epoch+1}/{num_epochs}], Loss : {loss.item():.4f}, Accuracy: {accuracy.item() * 100:.2f}%")


Epoch [10/100], Loss : 0.0607, Accuracy: 98.68%
Epoch [20/100], Loss : 0.0585, Accuracy: 98.68%
Epoch [30/100], Loss : 0.0565, Accuracy: 98.68%
Epoch [40/100], Loss : 0.0547, Accuracy: 98.90%
Epoch [50/100], Loss : 0.0529, Accuracy: 98.90%
Epoch [60/100], Loss : 0.0513, Accuracy: 98.90%
Epoch [70/100], Loss : 0.0497, Accuracy: 99.12%
Epoch [80/100], Loss : 0.0483, Accuracy: 99.12%
Epoch [90/100], Loss : 0.0469, Accuracy: 99.12%
Epoch [100/100], Loss : 0.0455, Accuracy: 99.34%


### 🔹 Training Loop Breakdown

```python
for epoch in range(num_epochs):
    model.train()
```

* Runs for `num_epochs` iterations.
* `model.train()` tells PyTorch we’re in **training mode** (important if your model had dropout/batchnorm).

---

```python
    optimizer.zero_grad()
```

* Clears out old gradients (otherwise PyTorch accumulates them every `.backward()`).

---

```python
    outputs = model(X_train)
```

* Feeds training data (`X_train`) into your model → produces predictions (`outputs`).

---

```python
    loss = criterion(outputs, y_train.view(-1,1))
```

* Computes the **loss** between predicted values and actual labels.
* `y_train.view(-1, 1)` reshapes `y_train` into a column vector so its shape matches `outputs`.

---

```python
    loss.backward()
    optimizer.step()
```

* **`loss.backward()`** → computes gradients via backpropagation.
* **`optimizer.step()`** → updates model weights using gradients (Adam optimizer in your case).

---

### 🔹 Accuracy Calculation

```python
    with torch.no_grad():
        predicted = outputs.round()
        correct = (predicted == y_train.view(-1,1)).float().sum()
        accuracy = correct / y_train.size(0)
```

* `torch.no_grad()` → disables gradient tracking (saves memory since we’re just evaluating).
* `outputs.round()` → since outputs are probabilities in `[0,1]`, rounding gives predicted labels (0 or 1).
* Compares predictions with true labels → counts how many are correct.
* `accuracy` = fraction of correctly predicted samples.

---

### 🔹 Logging

```python
    if (epoch+1) % 10 == 0:
        print(f"Epoch [{epoch+1}/{num_epochs}], Loss : {loss.item():.4f}, Accuracy: {accuracy.item() * 100:.2f}%")
```

* Every 10 epochs, it prints current loss & accuracy.

Sample output might look like:

```
Epoch [10/100], Loss: 0.4215, Accuracy: 82.00%
Epoch [20/100], Loss: 0.3156, Accuracy: 88.67%
...
```

---

### ✅ Summary

our loop does exactly what training should:

1. Forward pass
2. Compute loss
3. Backward pass (gradients)
4. Update weights
5. Track accuracy

---

⚡ Improvements we might consider:

* Shuffle & split data into **mini-batches** using `DataLoader` instead of feeding all `X_train` at once.
* Evaluate on a **validation/test set** inside the loop (not just training data).
* Use `BCEWithLogitsLoss` (and remove sigmoid) for numerical stability.


In [34]:
#model evaluation

#evaluate on training set
model.eval()
with torch.no_grad():
  outputs= model(x_train)
  predicted=outputs.round()
  correct = (predicted == y_train.view(-1,1)).float().sum()
  accuracy = correct / y_train.size(0)
  print(f"Accuracy on training data:{accuracy.item()*100:.2f}%")

Accuracy on training data:99.34%


In [35]:
#evaluate on test data:
model.eval()
with torch.no_grad():
  outputs= model(x_test)
  predicted=outputs.round()
  correct = (predicted == y_test.view(-1,1)).float().sum()
  accuracy = correct / y_test.size(0)
  print(f"Accuracy on training data:{accuracy.item()*100:.2f}%")

Accuracy on training data:99.12%
